language: node_js
node_js:
- '0.12'
deploy:
  provider: npm
  email: simon.menke@gmail.com
  api_key:
    secure: JaOng2OoaLHsF5fbtNl7w6sQY+1MQOdguAqzbpNGqnXprTPK91rOHTDDff8q73KwfJa5F0F0Z15Q5/ih7uC6G/3IzYdLPSONJcZv3lkdm3ihJSu4koEMICqj25eDMPLBFjx0aLvcFt6EjGHUJViNQq9dV9WQZbrGbV28yI1/OolKFHGyhQh6q9gk31dPv+XYBGzfzBSbzvnlEf1dP2Rhk1SnBpz2LfyN6N+tjJtFrvCe51XWisBxnwLmujNiCXHWwXA2r8jt4SO/k3+MN1MKf87a++woFjBxtkZTm/n9ZgSrR11X1qJH5+g7UOYDqLxz6VJm8LHdlmbfDgbiJsWT1fhF/9DAd6tvWSa4Hb6SUlq5mO26Z8FR48YtLpa0VYhukhKvI7B1SrC7M9l2nmBrqSn1KSkf/4SYO5N85vg9vMBURbrBjXlopyTbdUbQKDwDl6GHEXTSRjGrT7NBxcB7hAWTpZqf3v4OU9hT4EU7dH0CYIwT/qdB/UWhoqKaAVJUT4x0WFLgk/cwg6n91xTCYGEOC+Upc8RJFY94UmD9mSRCYY8UIjFnPDp2dW8Z0o7WPF+1lbDqlwZna0jgmMnHrMO5DT+ZL+UjUxk0bXEvmv+8V0KCypau6Ta9sr93GkIPuwsBGCfEqYQkt2W2wJEBl65QabORK6Dhg/TNHK5JGn8=
  on:
    tags: true
    repo: mrhenry/mr-angular-pages
